name: amifast-dev
dependencies:
  - python=3.7
  - pip
  - pip:
    - matplotlib
    - py-cpuinfo
    - pytest
    - coverage
    - pre-commit
    - mypy
    - sphinx
    - black
    - pylint
    - twine
